[package]
name = "unifi-gfm-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libm = "0.2.2"  # Option for f32 sin_cos calculations
nalgebra = "0.31.1"
plotters = "0.3.1"
unifi-gfm = { path = "../unifi-gfm" }